site_name: ShadowSim
site_description: Quantum simulation utilities (work in progress)
site_url: https://simsaidan.github.io/ShadowSim.py/
repo_url: https://github.com/simsaidan/ShadowSim.py
repo_name: simsaidan/ShadowSim.py

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md

plugins:
  - search
